
on: 
  workflow_dispatch:
    #manual - just for testing
  pull_request:
    branches:
      - master
    #manual - just for testing
  release: 
    types: [published]
    #if test succeeded, then push to repo
    
jobs:
  test:
    runs-on: windows-2022
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Branch name
        id: branch_name
        shell: bash
        run: |
          Write-Output ${GITHUB_REF}
          Write-Output ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          Write-Output ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          Write-Output ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}    
        
      - name: Install Choco
        run: |
           if(test-path -path "C:\ProgramData\chocolatey\choco.exe"){Write-Output "Choco is already installed"} else {
             [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
             Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
           }
        

        - name: GetPackages
        id: packages
        run: |
            $packages = Get-ChildItem -path . -recurse -Filter '*.nuspec' |Select-Object -ExpandProperty fullname
            $data = $packages | foreach-object {
                $path=$_
                [xml]$c=get-content $_ 
                $c.package.metadata |Select-Object -property id,version, @{n="repo";e={ $((choco search $($_.id) --version=$($_.version) --exact --detailed --pre --allowunofficial --limitoutput) | Measure-Object -line | Select-Object -expandproperty Lines  ) -eq 1  }}, @{n="path";e={$path}} 
            }
            $chocopackages=$data |ConvertTo-Json -Compress
            Write-Output "CHOCO_PACKAGES=$($chocopackages)" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Get Tag Base Name
        id: tagname
        env:
          SOURCE_TAG: ${{  steps.branch_name.outputs.SOURCE_TAG }}
        run: |
           Write-Output ${{ env.SOURCE_TAG }}
           if( '${{ env.SOURCE_TAG  }}' -eq 'refs/heads/master' ){
             $tag = 'mqtt-explorer-0.4.0-beta1'
             $itemname = $(( $tag | select-String -Pattern '(.*?)-[0-9]+.*' ).matches.groups[-1].value)
             if( $tag -match '-(open|beta|alpha|rc|preview|final)[0-9]*$' ) {
                Write-Output "CHOCO_PRE=--pre"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
             }              
             Write-Output $itemname
             Write-Output "CHOCO_ITEMNAME=$itemname"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append          
            } else {
             Write-Output "CHOCO_ITEMNAME=$((  ${{ env.SOURCE_TAG }} | Select-String -Pattern '(.*?)-[0-9]+.*' ).matches.groups[-1].value)"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
             if( '${{ env.SOURCE_TAG }}' -match '-(open|beta|alpha|rc|preview|final)[0-9]*$' ) {
                Write-Output "CHOCO_PRE=--pre"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
             } 
            }

      - name: Get Path of item
        id: itempath
        env:
          CHOCO_PACKAGES: ${{  env.CHOCO_PACKAGES }}
          CHOCO_ITEMNAME: ${{  env.CHOCO_ITEMNAME }}
        run: |
           $choco_packages='${{env.CHOCO_PACKAGES}}' | convertfrom-json 
           write-output $choco_packages
           write-output "CHOCO_ITEMPATH=$( ($choco_packages).where({$_ -match  '${{ env.CHOCO_ITEMNAME }}'  }) )"   | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append     

      - name: Choco Pack
        id: chocopack        
        env:
          CHOCO_ITEMPATH: ${{ env.CHOCO_ITEMPATH }}        
        run: |
           choco pack ${{ env.CHOCO_ITEMPATH }}
 
      - name: Choco Install
        id: chocoinstall
        env:
          CHOCO_ITEMNAME: ${{  env.CHOCO_ITEMNAME }}        
          CHOCO_PRE: ${{  env.CHOCO_PRE }}      
        run: |
           choco install -s . ${{ env.CHOCO_ITEMNAME }} ${{ env.CHOCO_PRE }}
           
      - name: Choco uninstall
        id: chocouninstall
        env:
          CHOCO_ITEMNAME: ${{  env.CHOCO_ITEMNAME }}          
        run: |
           choco uninstall  ${{ env.CHOCO_ITEMNAME }}
  push:
    needs: test
    runs-on: windows-2022
    if: github.event_name == 'release'
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Branch name
        id: branch_name
        shell: bash
        run: |
          write-output ${GITHUB_REF}
          write-output ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          write-output ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          write-output ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}    
        
      - name: Install Choco
        run: |
           if(test-path -path "C:\ProgramData\chocolatey\choco.exe"){write-output "Choco is already installed"} else {
             [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
             Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
           }
        
      - name: SetAPIKey
        run: | 
          choco apikey --key CHOCO_API_KEY --source CHOCO_SRC_URL        
      
      - name: GetPackages
        id: packages
        run: |
           $packages = Get-ChildItem -path . -recurse -Filter '*.nuspec' |Select-Object -ExpandProperty fullname
           $data = $packages | foreach-object {
             $path=$_
             [xml]$c=get-content $_ 
             $c.package.metadata |Select-Object -property id,version, @{n="repo";e={ $((choco search $($_.id) --version=$($_.version) --exact --detailed --pre --allowunofficial --limitoutput) | Measure-Object -line | Select-Object -expandproperty Lines  ) -eq 1  }}, @{n="path";e={$path}} 
            }
            $chocopackages=$data |ConvertTo-Json -Compress
            #id            version     repo path
            #--            -------     ---- ----
            # mqtt-explorer 0.4.0-beta1 True C:\Users\..
           write-output "CHOCO_PACKAGES=$($chocopackages)" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Get Tag Base Name
        id: tagname
        env:
          SOURCE_TAG: ${{  steps.branch_name.outputs.SOURCE_TAG }}
        run: |
           write-output ${{ env.SOURCE_TAG }}
           if( '${{ env.SOURCE_TAG  }}' -eq 'refs/heads/master' ){
             $tag = 'mqtt-explorer-0.4.0-beta1'
             $itemname = $(( $tag | select-String -Pattern '(.*?)-[0-9]+.*' ).matches.groups[-1].value)
             if( $tag -match '-(open|beta|alpha|rc|preview|final)[0-9]*$' ) {
                write-output "CHOCO_PRE=--pre"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
             }              
             write-output $itemname
             write-output "CHOCO_ITEMNAME=$itemname"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append          
            } else {
             $itemname = $(( '${{ env.SOURCE_TAG }}' | Select-String -Pattern '(.*?)-[0-9]+.*' ).matches.groups[-1].value)
             $itemver =  "${{ env.SOURCE_TAG }}".substring($itemname.length+1)
             write-output "CHOCO_ITEMNAME=$itemname"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
             write-output "CHOCO_ITEMVER= $itemname"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
             if( '${{ env.SOURCE_TAG }}' -match '-(open|beta|alpha|rc|preview|final)[0-9]*$' ) {
                write-output "CHOCO_PRE=--pre"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
             } 
            }
      
      - name: Get Path of item
        id: itempath
        env:
          CHOCO_PACKAGES: ${{  env.CHOCO_PACKAGES }}
          CHOCO_ITEMNAME: ${{  env.CHOCO_ITEMNAME }}
        run: |
           $choco_packages='${{env.CHOCO_PACKAGES}}'.split(';')
           write-output $choco_packages
           write-output "CHOCO_ITEMPATH=$( ($choco_packages).where({$_ -match  '${{ env.CHOCO_ITEMNAME }}'  }) )"   | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append     

      - name: Choco Pack
        id: chocopack        
        env:
          CHOCO_ITEMPATH: ${{ env.CHOCO_ITEMPATH }}        
        run: |
           choco pack ${{ env.CHOCO_ITEMPATH }}

                 
     # - name: Push
     #   uses: crazy-max/ghaction-chocolatey@v1
     #   with:
     #     args: push ${{  steps.item_tag.outputs.result  }}.nupkg --source CHOCO_SRC_URL
 
